"""add area tabel

Revision ID: 970877781d54
Revises: 614e7d81aa6c
Create Date: 2022-05-01 18:57:32.478109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970877781d54'
down_revision = '614e7d81aa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    # ### end Alembic commands ###
